import { useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../api/client';
import type { SupportCase } from '../api/types';

export function CustomerPortal() {
  const navigate = useNavigate();
  const [form, setForm] = useState({ name: 'Ananya Rao', email: 'ananya.rao@example.in', subject: '₹2,499 deducted but my order was not placed', issue: 'My payment was successful and ₹2,499 was deducted, but I do not see an order. Please resolve this.' });
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const d = await api.post<{case: SupportCase; portal:{caseId:string;token:string}}>('/portal/cases', form); navigate(`/customer/case?caseId=${encodeURIComponent(d.portal.caseId)}&token=${encodeURIComponent(d.portal.token)}`); } catch(err) { setError(err instanceof Error ? err.message : 'Could not submit your request.'); } finally { setBusy(false); } }
  return <div className="min-h-screen bg-canvas"><header className="border-b border-line bg-surface px-6 py-4"><div className="mx-auto flex max-w-5xl items-center justify-between"><div><p className="text-lg font-semibold">ResolveAI</p><p className="text-xs text-muted">Customer support portal</p></div><a className="text-xs underline" href="/login">Staff sign in</a></div></header><main className="mx-auto grid max-w-5xl gap-8 px-6 py-12 lg:grid-cols-[1fr_24rem]"><section><p className="text-micro uppercase tracking-[0.18em] text-muted">Autonomous support</p><h1 className="mt-3 max-w-2xl text-4xl font-semibold tracking-tight">Tell us what went wrong. Your AI support teammate will investigate it.</h1><p className="mt-4 max-w-xl text-muted">ResolveAI checks your payment, order and account context, applies support policy, and either resolves the case or brings a human the evidence they need.</p><div className="mt-10 grid gap-3 sm:grid-cols-3">{[['01','Understand','Your issue becomes a named case.'],['02','Investigate','Payment and account evidence is gathered.'],['03','Resolve','A safe action is executed and verified.']].map(x=><div key={x[0]} className="panel p-4"><span className="figure text-xs text-muted">{x[0]}</span><p className="mt-4 font-medium">{x[1]}</p><p className="mt-1 text-xs text-muted">{x[2]}</p></div>)}</div></section><form onSubmit={submit} className="panel p-5"><h2 className="font-semibold">Open a support case</h2><p className="mt-1 text-xs text-muted">We'll use this email to keep you updated.</p>{[['name','Name'],['email','Email'],['subject','Case name / subject']].map(([key,label])=><label key={key} className="mt-4 block text-sm font-medium">{label}<input className="field mt-1.5" type={key==='email'?'email':'text'} value={(form as any)[key]} onChange={e=>setForm({...form,[key]:e.target.value})} required /></label>)}<label className="mt-4 block text-sm font-medium">What happened<textarea className="field mt-1.5 min-h-32" value={form.issue} onChange={e=>setForm({...form,issue:e.target.value})} required /></label>{error&&<p className="mt-4 rounded border border-blocked/30 bg-blocked/5 p-3 text-sm text-blocked">{error}</p>}<button className="btn-primary mt-5 w-full" disabled={busy}>{busy?'AI teammate is accepting the case…':'Submit to ResolveAI'}</button></form></main></div>;
}
